version: '3.8'

services:
  bmq:
    build:
      platforms: 
        - "linux/arm64"
      context: .
      dockerfile: bmq.Dockerfile
    depends_on:
      - redis-service

  redis-service:
    platform: "linux/arm64"
    image: public.ecr.aws/docker/library/redis:7.2-alpine
    ports:
      - '6379:6379'
    restart: always
